wait("ZagolovokConfigurator.png")
click("Servis.png")
click("Parametri.jpg")
wait("1ZakladkaZapusk.png")
click("1ZakladkaZapusk.png")
click("2ZakladkaDopolnitelnie.png")
click("3RadioZapuskatiKakaManager.png")
click("4KnokaPrimeniti.png")
click("5KnopkaOk.png")
click("9KnopkaNachatiOtladku.png")

